name: HashiCorp vault with github actions

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to HashiCorp vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{secrets.VAULT_ADDRESS}}
          token: ${{ secrets.VAULT_TOKEN }}
          method: token
          secrets: |
            Secrets/kv/test/github-actions email
            Secrets/kv/test/github-actions password

      - name: Mask and print keys (safe logging)
        run: |
          echo "::add-mask::${{ steps.vault.outputs.email }}"
          echo "::add-mask::${{ steps.vault.outputs.password }}"
          echo "Fetched email: ${{ steps.vault.outputs.email }}"
          echo "Fetched password: ${{ steps.vault.outputs.password }}"
