name: HashiCorp vault with github actions

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to HashiCorp vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{secrets.VAULT_ADDRESS}}
          token: ${{ secrets.VAULT_TOKEN }}
          method: token
