name: HashiCorp vault with github actions

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      # - name: Login to HashiCorp vault and fetch secrets
      #   id: vault                
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ secrets.VAULT_ADDRESS }}
      #     token: ${{ secrets.VAULT_TOKEN }}
      #     secrets: |
      #       kv/data/test/github-actions email

      - name: Print key
        run: echo "Fetched email = ${{ secrets.VAULT_TOKEN }}"
